fortune_dict = {
    0:"You are gona do something good for your country",
    1:"You will get success, the day you start working hard and consistent.",
    2:"You will face lot's of challanges in life but you will tackle them all.",
    3:"You are gona fall in love soon.",
    5:"You are gona be very rich because of your investments.",
    6:"Soon you will recognise the love of your life.",
    7:"Follow your passion it is the key to your success.",
    8:"You are gona have sex with more than 2 people in your life. XD",
    9:"You are gona have sex with more than 5 people in your life. XD",
    10:"You are gona have sex with more than 10 people in your life. XD",
    11:"You will meet you life partner in a Library.",
    12:"You are gona experience WORLD WAR 3.",
    13:"You will play a major role in your life partners well being. Make sure you take good care of them.",
    14:"You will play a major role in your parents well being. Make sure you take good care of them.",
    15:"Things are gona be rough, but remember to be focused on your main goal.",
    16:"You are gona be rich with your NFT investments.",
    17:"You will become a big whale in future.",
    18:"Even in tough time you must remeber who you are and what you are capable of.(dont think less of yourself).",
    19:"The days are gona be dark ahed make sure you prepare for the worse.",
    20:"You are gona meet god in real life but you wont recognise him.",
    21:"You are gona die as a HERO.",
    22:"Karma is gona make fun of those you made fun of you earlier.",
    23:"Karma is a bitch and it will bite your hater in the ass.",
    24:"You will have the opportunity to explore Mars.",
    25:"You are gona participate in WORLD WAR 3.",
    26:"Nasa will contact You for some work.",
    27:"You are gona take profits at market top.",
    28:"You will fall in love with 3 person in your whole life time.",
    29:"You will start your own business one day.",
    30:"You are gona make lots of money gambling.",
    31:"You are gona lose lots of money gambling.",
    32:"You will experience alot of abundance in your life.",
    33:"You will be protected by the will of god.",
    34:"You will have a lot of Negative taughts about deamons.",
    35:"There is a good opportunity coming your way.",
    36:"You will experience a lot of Creative Energy.",
    37:"You will inspire people around you.",
    38:"The result you have been waiting for will turn positive.",
    39:"You will be conquering a major illness",
    40:"You will soon get your lucky charm.",
    41:"Today is your lucky day.You will get lucky.",
    42:"Today is not your lucky day dont gamble",
    43:"You are gona meet a deamon which will fall in love with you and haunt you.",
    44:"You will win a lottery today.",
    45:"you will get the thing you desire from the bottom of your heart.",
    46:"There is a possibility of you getting laid today.",
    47:"You will experience a threesome in life",
    48:"You will experience a foursome in life.",
    49:"You will not die a virgin.",
    50:"You will die falling from a plane."
}