fortune_dict = {
    0:"You are gona do something good for your country",
    1:"You will get success, the day you start working hard and consistent.",
    2:"You will face lot's of challanges in life but you will tackle them all.",
    3:"You are gona fall in love soon.",
    5:"You are gona be very rich because of your investments.",
    6:"Soon you will recognise the love of your life.",
    7:"Follow your passion it is the key to your success.",
    8:"You are gona have sex with more than 2 people in your life. XD",
    9:"You are gona have sex with more than 5 people in your life. XD",
    10:"You are gona have sex with more than 10 people in your life. XD",
    11:"You will meet you life partner in a Library.",
    12:"You are gona experience WORLD WAR 3.",
    13:"You will play a major role in your life partners well being. Make sure you take good care of them.",
    14:"You will play a major role in your parents well being. Make sure you take good care of them.",
    15:"Things are gona be rough, but remember to be focused on your main goal.",
    16:"You are gona be rich with your NFT investments.",
    17:"You will become a big whale in future.",
    18:"Even in tough time you must remeber who you are and what you are capable of.(dont think less of yourself).",
    19:"The days are gona be dark ahed make sure you prepare for the worse.",
    20:"You are gona meet god in real life but you wont recognise him.",
    21:"You are gona die as a HERO.",
    22:"Karma is gona make fun of those you made fun of you earlier.",
    23:"Karma is a bitch and it will bite your hater in the ass.",
    24:"You will have the opportunity to explore Mars.",
    25:"You are gona participate in WORLD WAR 3.",
    26:"Nasa will contact You for some work.",
    27:"You are gona take profits at market top.",
    28:"You will fall in love with 3 person in your whole life time.",
    29:"You will start your own business one day.",
    30:"You are gona make lots of money gambling.",
    31:"You are gona lose lots of money gambling.",
    32:"You will experience alot of abundance in your life.",
    33:"You will be protected by the will of god.",
    34:"You will have a lot of Negative taughts about deamons.",
    35:"There is a good opportunity coming your way.",
    36:"You will experience a lot of Creative Energy.",
    37:"You will inspire people around you.",
    38:"The result you have been waiting for will turn positive.",
    39:"You will be conquering a major illness",
    40:"You will soon get your lucky charm.",
    41:"Today is your lucky day.You will get lucky.",
    42:"Today is not your lucky day dont gamble",
    43:"You are gona meet a deamon which will fall in love with you and haunt you.",
    44:"You will win a lottery today.",
    45:"you will get the thing you desire from the bottom of your heart.",
    46:"There is a possibility of you getting laid today.",
    47:"You will experience a threesome in life",
    48:"You will experience a foursome in life.",
    49:"You will not die a virgin.",
    50:"You will die falling from a plane.",
    51:"Sickness of a friend. Go at Once!",
    52:"You will soon have cause to forget your money trouble.",
    53:"A short trip coming and it's Important!",
    54:"You may get a ring in near future.",
    55:"Great Disappointment ahed.",
    56:"Your next love affair will surprise you.",
    57:"Good news in two weeks.",
    58:"Small sum of money coming to you.",
    59:"Look out for trouble within a few days.",
    60:"You are going to move to a new house.",
    61:"You are going to marry sooner than you expect.",
    62:"Pleasant news incoming to you.",
    63:"A scandal will be barely escaped.",
    64:"A wedding in the near future.",
    65:"Marriage Ahed!",
    66:"A flase friend Beware.",
    67:"You hvae been wishing for something. Do not give up hope.",
    68:"A meeting soon with some one who will be intrested in you.",
    69:"A pleasant Surprise Ahed!",
    70:"Do not talk too much --Listen",
    71:"Do not wait too long before saying Yes.",
    72:"Money coming to you -- but a little trouble about it.",
    73:"A stranger will ask you to the theatre. Accept",
    74:"You have a few worthy freinds and one unexpected enemy.",
    75:"Live your own life Dont put your nose in others life.",
    76:"A long trip in the near future.",
    77:"You will shortly occupy a strange bed.",
    78:"You hvae people near you who are not true.",
    79:"Next winter you will go on a long trip.",
    80:"A turn for the better.",
    81:"You business will be poof for a short time.",
    82:"Be careful in your business dealing for the next few days.",
    83:"You have many freinds but one is not loyal to you.",
    84:"Your wish will be granted to you.",
    85:"You will hear something unpleasant.",
    86:"Hapiness from an unexpected source.",
    87:"Money is going to be willed to you.",
    88:"Wealth beyond your fondest dreams.",
    89:"You know him -- but not as well as you think.",
    90:"Be very kind when you meet your newest freind.",
    91:"The one you marry will bring you wealth.",
    92:"An engagement will be broken because of you.",
    93:"A friend is false -- but keep your own council.",
    94:"A jealous Woman!",
    95:"Be very very careful when you see a certain blonde.",
    96:"A woman will soon invite you to her home. Go!",
    97:"You will soon meet the one you most want to meet.",
    98:"Do not give him any hope.",
    99:"A new friend will mean the turning point in your life.",
    100:"Death of a friend.",
    101:"Soon you will get a present",
    102:"So you wll get a important Letter.",
    103:"A sudden Journey ahed.",
    104:"Good luck will be with you early in the month.",
    105:"A surprise is waiting for you in the near future.",
    106:"An enjoyable trip for you soon.",
    107:"Guests coming means trouble.",
    108:"The one who cares for you is anxious for a letter.",
    109:"You have long been loved by the one you least expected.",
    110:"You own someone a letter write it at once.",
    111:"You will hear of a wedding and be disappointed.",
    112:"You are going to marry more than once.",
    113:"Good business in sight.",
    114:"A conference that will benefit you.",
    115:"You are not shrewd enough.",
    116:"A dinner Invitation in near future.",
    117:"You will be invited to a party. Think before you accept!",
    118:"A long motor trip with a surprise at the end.",
    119:"A stranger who will turn into a good friend.",
    120:"A dark woman is trying to get you into trouble.",
    121:"Seven is your Lucky number.",
    122:"Do not let talk of a jealous person bother you.",
    123:"You want money. Be patient ",
    124:"Be cheerful -- no matter what happens",
    125:"A woman is coming between you and your beloved.",
    126:"A relative is going to be ill, but will recover.",
    127:"You will sell something and get a good price.",
    128:"Good Luck coming to you.",
    129:"A big surprise coming to you.",
    130:"Your lifes romance is about to begain.",
    131:"Pay no attention to something you are going to hear.",
    132:"A change in the life of a true friend.",
    133:"Keep you courage a little longer, better things aligned for you.",
    134:"No matter what he says dont trust him.",
    135:"You are continually in some ones taughts.",
    136:"You are going to be happier than you dared hope.",
    137:"A pretty woman wants to see you. Avoide her.",
    138:"A woman is going to tell a lie that will hurt you.",
    139:"The best friend you have will help you.",
    140:"A present will be offered to you, refuse it.",
    141:"A letter, Act on it at once.",
    142:"You need self confidence otherwise you will lose.",
    143:"A man is working to make things come out right for you.",
    144:"Your partner is blindly in love with you.",
    145:"you partner is a psycho who can even kill for you.",
    146:"Drama in your near future.",
    147:"Not completing your task on time will get you in trouble.",
    148:"Complete your work on time you will achieve success.",
    149:"Help your friend today, He will help you in a time when you really need it.",
    150:"You will be offered Tasty food soon"
}